#Data.sh applies the rubric for a dialect to a collection. This creates the data.csv that
#a RAD.xlsx functions on. It requires three arguments. The first is the organization the second 
#is the dialect, DataOne the third is the collection. GetData.sh is the batch script for Data.sh

./UseRosetta.sh DataOne CDL CSDGM  
./UseRosetta.sh DataOne CLOEBIRD EML
./UseRosetta.sh DataOne Dryad Dryad
./UseRosetta.sh DataOne EDACGSTORE CSDGM
./UseRosetta.sh DataOne EDORA Mercury
./UseRosetta.sh DataOne ESA EML
./UseRosetta.sh DataOne GLEON EML
./UseRosetta.sh DataOne GOA EML
./UseRosetta.sh DataOne IARC Onedcx
./UseRosetta.sh DataOne IOE EML
./UseRosetta.sh DataOne KNB EML
./UseRosetta.sh DataOne KUBI EML
./UseRosetta.sh DataOne LTER EML
./UseRosetta.sh DataOne LTER_EUROPE EML
./UseRosetta.sh DataOne NMEPSCOR CSDGM
./UseRosetta.sh DataOne ONEShare EML 
./UseRosetta.sh DataOne ORNLDAAC Mercury 
./UseRosetta.sh DataOne PISCO EML
./UseRosetta.sh DataOne RGD Mercury
./UseRosetta.sh DataOne SANPARKS EML
./UseRosetta.sh DataOne SEAD CSDGM
./UseRosetta.sh DataOne TERN EML
./UseRosetta.sh DataOne TFRI EML
./UseRosetta.sh DataOne US_MPC Onedcx
./UseRosetta.sh DataOne USANPN EML
./UseRosetta.sh DataOne USGSCSAS BDP
./UseRosetta.sh DataOne USGSCSAS CSDGM
./UseRosetta.sh IEDA ECL DCITE
./UseRosetta.sh IEDA MarineGeoscienceDataSystem ISO
./UseRosetta.sh USGS ScienceBase CSDGM
./UseRosetta.sh USGS OldScienceBase CSDGM  
./UseRosetta.sh NCAR RDA RDA-CISL
./UseRosetta.sh NCAR IIS MODS
./UseRosetta.sh BCO-DMO GeoTraces ISO
#./UseRosetta.sh BCO-DMO ISO GeoTraces_summer2016
./UseRosetta.sh NASA GES_DISC DIF
./UseRosetta.sh NASA GHRC DIF
./UseRosetta.sh NASA LARC DIF
./UseRosetta.sh NASA GHRC ISO
./UseRosetta.sh NASA LARC ISO
./UseRosetta.sh NASA NSIDC ISO
./UseRosetta.sh NASA NSIDC DIF
./UseRosetta.sh ORNL USGSC CSDGM
./UseRosetta.sh ORNL NGEE CSDGM
./UseRosetta.sh ORNL DAAC Mercury
./UseRosetta.sh ORNL OLI ISO
./UseRosetta.sh LTERthroughTime LTER_2005 EML
./UseRosetta.sh LTERthroughTime LTER_2006 EML
./UseRosetta.sh LTERthroughTime LTER_2007 EML
./UseRosetta.sh LTERthroughTime LTER_2008 EML
./UseRosetta.sh LTERthroughTime LTER_2009 EML
./UseRosetta.sh LTERthroughTime LTER_2010 EML
./UseRosetta.sh LTERthroughTime LTER_2011 EML
./UseRosetta.sh LTERthroughTime LTER_2012 EML
./UseRosetta.sh LTERthroughTime LTER_2013 EML
./UseRosetta.sh LTERthroughTime LTER_2014 EML
./UseRosetta.sh LTERthroughTime LTER_2015 EML
./UseRosetta.sh LTERthroughTime LTER_2016 EML