#Data.sh applies the rubric for a dialect to a collection. This creates the data.csv that
#a RAD.xlsx functions on. It requires three arguments. The first is the organization the second 
#is the dialect, the third is the collection. GetData.sh is the batch script for Data.sh

./Data.sh DataOne CSDGM CDL   
./Data.sh DataOne EML CLOEBIRD
./Data.sh DataOne Dryad Dryad
./Data.sh DataOne Dryad Dryad
./Data.sh DataOne CSDGM EDACGSTORE
./Data.sh DataOne Mercury EDORA
./Data.sh DataOne EML ESA
./Data.sh DataOne EML GLEON
./Data.sh DataOne EML GOA
./Data.sh DataOne Onedcx IARC
./Data.sh DataOne EML IOE
./Data.sh DataOne EML KNB
./Data.sh DataOne EML KUBI
./Data.sh DataOne EML LTER
./Data.sh DataOne EML LTER_EUROPE
./Data.sh DataOne CSDGM NMEPSCOR
./Data.sh DataOne EML ONEShare
./Data.sh DataOne Mercury ORNLDAAC
./Data.sh DataOne EML PISCO
./Data.sh DataOne Mercury RGD
./Data.sh DataOne EML SANPARKS
./Data.sh DataOne CSDGM SEAD
./Data.sh DataOne EML TERN
./Data.sh DataOne EML TFRI
./Data.sh DataOne Onedcx US_MPC
./Data.sh DataOne EML USANPN
./Data.sh DataOne BDP USGSCSAS
./Data.sh DataOne CSDGM USGSCSAS
./Data.sh IEDA DCITE ECL
./Data.sh IEDA ISO MarineGeoscienceDataSystem
./Data.sh USGS CSDGM ScienceBase 
./Data.sh USGS CSDGM OldScienceBase  
./Data.sh NCAR RDA-CISL RDA
./Data.sh NCAR MODS IIS
./Data.sh BCO-DMO ISO GeoTraces
#./Data.sh BCO-DMO ISO GeoTraces_summer2016
./Data.sh NASA DIF GES_DISC
./Data.sh NASA DIF GHRC
./Data.sh NASA DIF LARC
./Data.sh NASA ISO GHRC
./Data.sh NASA ISO LARC
./Data.sh NASA ISO NSIDC
./Data.sh NASA DIF NSIDC
./Data.sh ORNL CSDGM USGSC
./Data.sh ORNL CSDGM NGEE
./Data.sh ORNL Mercury DAAC
./Data.sh ORNL ISO OLI
./Data.sh LTERthroughTime EML LTER_2005
./Data.sh LTERthroughTime EML LTER_2006
./Data.sh LTERthroughTime EML LTER_2007
./Data.sh LTERthroughTime EML LTER_2008
./Data.sh LTERthroughTime EML LTER_2009
./Data.sh LTERthroughTime EML LTER_2010
./Data.sh LTERthroughTime EML LTER_2011
./Data.sh LTERthroughTime EML LTER_2012
./Data.sh LTERthroughTime EML LTER_2013
./Data.sh LTERthroughTime EML LTER_2014
./Data.sh LTERthroughTime EML LTER_2015
./Data.sh LTERthroughTime EML LTER_2016