./rawData.sh DataOne CSDGM CDL   
./rawData.sh DataOne EML CLOEBIRD
./rawData.sh DataOne Dryad Dryad
./rawData.sh DataOne Dryad Dryad
./rawData.sh DataOne CSDGM EDACGSTORE
./rawData.sh DataOne Mercury EDORA
./rawData.sh DataOne EML ESA
./rawData.sh DataOne EML GLEON
./rawData.sh DataOne EML GOA
./rawData.sh DataOne Onedcx IARC
./rawData.sh DataOne EML IOE
./rawData.sh DataOne EML KNB
./rawData.sh DataOne EML KUBI
./rawData.sh DataOne EML LTER
./rawData.sh DataOne EML LTER_EUROPE
./rawData.sh DataOne CSDGM NMEPSCOR
./rawData.sh DataOne EML ONEShare
./rawData.sh DataOne Mercury ORNLDAAC
./rawData.sh DataOne EML PISCO
./rawData.sh DataOne Mercury RGD
./rawData.sh DataOne EML SANPARKS
./rawData.sh DataOne CSDGM SEAD
./rawData.sh DataOne EML TERN
./rawData.sh DataOne EML TFRI
./rawData.sh DataOne Onedcx US_MPC
./rawData.sh DataOne EML USANPN
./rawData.sh DataOne BDP USGSCSAS
./rawData.sh DataOne CSDGM USGSCSAS
./rawData.sh IEDA DCITE ECL
./rawData.sh IEDA ISO MarineGeoscienceDataSystem
./rawData.sh USGS CSDGM ScienceBase 
./rawData.sh USGS CSDGM OldScienceBase  
./rawData.sh NCAR RDA-CISL RDA
./rawData.sh BCO-DMO ISO GeoTraces
./rawData.sh NASA DIF GES_DISC
./rawData.sh NASA DIF GHRC
./rawData.sh NASA DIF LARC
./rawData.sh NASA ISO GHRC
./rawData.sh NASA ISO LARC
./rawData.sh NASA ISO NSIDC
./rawData.sh NASA DIF NSIDC
./rawData.sh ORNL CSDGM USGSC
./rawData.sh ORNL CSDGM NGEE
./rawData.sh ORNL Mercury DAAC
./rawData.sh ORNL ISO OLI
